<a href="https://colab.research.google.com/github/benyizhang/Book1_Python-For-Beginners/blob/main/Twitter_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Twitter data clean
- The analysis is conducted using Anaconda distribution
- The raw data is extracted using `Twitter_API.py`.
- Here is my new version. This test version seems to work. So the github works as I expected. The notebook works as I expected.

- `pip install -r requirement_colab.txt` to install packages for google colab. Run this code in terminal. The package will have to be installed everytime when I open the notebook.

In [2]:
# Load all necessary packages
from os import getcwd, listdir, chdir
# package to read and write files from and to google drive
from google.colab import drive
drive.mount('/content/drive')
# Show working directory
print(f'The original working directionary is {getcwd()}', '\n')
# change my working directory to KJBZ_TS_2024
chdir('/content/drive/MyDrive/IES_FSV/Phd_Research/KJBZ_TS_2024')
# Show new working directory
print(f'The original working directionary is {getcwd()}', '\n')

Mounted at /content/drive
The original working directionary is /content 

The original working directionary is /content/drive/MyDrive/IES_FSV/Phd_Research/KJBZ_TS_2024 



In [3]:
# package install
# use quiet to hide the output
!pip install -r requirement_colab.txt --quiet # we can run this in terminal

# package load
import numpy as np
import pandas as pd
import uuid

# Jupyter show code execution time
%load_ext autotime

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 586.9/586.9 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 MB 28.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 69.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 25.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.7/110.7 kB 10.1 MB/s eta 0:00:00
time: 313 µs (started: 2024-11-07 15:27:33 +00:00)


In [81]:
# load data: raw data
twitter_data = pd.read_csv('Sentiment_data/Data/Twitter_data_raw.csv')
# show data
twitter_data.head(5)

Tweet_id              User_name Quarter    Month        Date  \
0  1843589871354687499                   ACBF  2024Q4  2024-10  2024-10-08   
1  1843589357233668262               ALI MUSA  2024Q4  2024-10  2024-10-08   
2  1843589257061118009  Agape Earth Coalition  2024Q4  2024-10  2024-10-08   
3  1843588048719937699              Swedwatch  2024Q4  2024-10  2024-10-08   
4  1843588037269434754              Armando R  2024Q4  2024-10  2024-10-08   

                        Time  \
0  2024-10-08 09:50:52+00:00   
1  2024-10-08 09:48:49+00:00   
2  2024-10-08 09:48:25+00:00   
3  2024-10-08 09:43:37+00:00   
4  2024-10-08 09:43:34+00:00   

                                                Text Lang  Bookmarks  View  \
0  Today is the day!\nJoin our side events in Abi...   en        0.0     2   
1  @eve_chantel Climate finance distribution perp...   en        0.0     3   
2  Sources of climate finance:\n\n1.⁠ ⁠Government...   en        0.0    12   
3  🕊️ We are calling for climate change policy to...   en        0.0    16   
4  We urgently need to decolonise climate finance...   en        0.0    17   

   Retweets  Like  Quotes  Replies  \
0       0.0   0.0     0.0      0.0   
1       0.0   1.0     0.0      0.0   
2       0.0   0.0     0.0      0.0   
3       0.0   0.0     0.0      0.0   
4       0.0   0.0     0.0      0.0   

                                             Hastags  
0          [{'indices': [273, 278], 'text': 'ATTS'}]  
1  [{'indices': [202, 212], 'text': 'ACCAC2024'},...  
2  [{'indices': [170, 180], 'text': 'ACCAC2024'},...  
3    [{'indices': [263, 274], 'text': 'PeaceAtCOP'}]  
4                                                NaN

time: 1.85 s (started: 2024-11-07 16:13:26 +00:00)


In [82]:
# show data shape
print(twitter_data.shape)

# show data type
print(twitter_data.dtypes)

(305653, 15)
Tweet_id       int64
User_name     object
Quarter       object
Month         object
Date          object
Time          object
Text          object
Lang          object
Bookmarks    float64
View           int64
Retweets     float64
Like         float64
Quotes       float64
Replies      float64
Hastags       object
dtype: object
time: 1.54 ms (started: 2024-11-07 16:13:39 +00:00)


In [83]:
# change data type: Tweet_id from int64 to string
twitter_data['Tweet_id'] = twitter_data['Tweet_id'].astype(str)
# change number types: these columns should be integers.
twitter_data[['Bookmarks', 'View', 'Retweets', 'Like','Quotes','Replies']] = twitter_data[['Bookmarks', 'View', 'Retweets', 'Like','Quotes','Replies']].astype(int)

time: 104 ms (started: 2024-11-07 16:13:39 +00:00)


In [84]:
# mask user_name by creating UUID
user_name = twitter_data['User_name'].unique()
user_id = np.array([str(uuid.uuid4()) for _ in user_name])
uuid_mapping = dict(zip(user_name, user_id))

time: 377 ms (started: 2024-11-07 16:13:39 +00:00)


In [85]:
# map uuid back to twiiter_data.
twitter_data.insert(2, 'User_id', twitter_data['User_name'].map(uuid_mapping))
# remove these three items, we don't beed it anymore.
del user_name, user_id, uuid_mapping

time: 53.2 ms (started: 2024-11-07 16:13:39 +00:00)


In [86]:
# show user name and their uuid
twitter_data.sort_values('User_name').head(5).iloc[0:5, 0:3] # The User_id is unique for each user_name

Tweet_id                                     User_name  \
269185   509219806340333568                                RAJVIR KASHYAP   
226414   788452568766840832                                          ndsn   
210399   875063236235808768                                          ndsn   
18272   1781453276447174942  !MAD-JesusDavid-stLALiVE! ART !2-4️⃣-5😎🇨🇭🌙🇬🇧   
53246   1614735596215214084  !MAD-JesusDavid-stLALiVE! ART !2-4️⃣-5😎🇨🇭🌙🇬🇧   

                                     User_id  
269185  98d011aa-dcd9-4ae6-bf1a-c12990219267  
226414  958d65a4-e99e-4f87-812e-58df5eb56338  
210399  958d65a4-e99e-4f87-812e-58df5eb56338  
18272   4b4c1284-1069-4ad2-8357-ed8c4497cfb2  
53246   4b4c1284-1069-4ad2-8357-ed8c4497cfb2

time: 444 ms (started: 2024-11-07 16:13:39 +00:00)


In [87]:
# show some user_id, and their text message
twitter_data.sort_values('Text')[['Tweet_id', 'User_name', 'User_id', 'Text']].head(6)

Tweet_id         User_name  \
37289   1701620411304226994       Drmikemyers   
37604   1701214173605081307       Drmikemyers   
37010   1702060486718636527       Drmikemyers   
37646   1701183679882494145       Drmikemyers   
208766   881770320692117505        Soil'nSoul   
289476   281411117807452160  Tree Credits Fnd   

                                     User_id  \
37289   cb6672b8-e9e9-426b-9a3d-42bd26640153   
37604   cb6672b8-e9e9-426b-9a3d-42bd26640153   
37010   cb6672b8-e9e9-426b-9a3d-42bd26640153   
37646   cb6672b8-e9e9-426b-9a3d-42bd26640153   
208766  145a0ca4-71c3-4f6f-8aea-16c1b16af129   
289476  073e2bbd-d51c-439e-8434-ec510f4cb51a   

                                                     Text  
37289   ! #TuckerCarlson #NASA #trump #whitehouse\n\nB...  
37604   ! #TuckerCarlson #NASA #trump #whitehouse\n\nB...  
37010   ! #TuckerCarlson #NASA #trump #whitehouse\n\nB...  
37646   ! #TuckerCarlson #NASA #trump #whitehouse\n\nU...  
208766  ! Green finance: The hunt for pennies on the p...  
289476  !! Not for the carbon: re-thinking climate fin...

time: 704 ms (started: 2024-11-07 16:13:40 +00:00)


## Data clean process
My twitter data has following issues:
- Unwanted special characteristics
  - Remove a list of users:
    - These users are excluded from our sample because they produce irrelevant information (e.g. prostitution adv).  
    - The reason they were initially included is due to their use of the "#" , for exmaple "#greenbond".    
  - Remove wanted people and unwanted tweet text.
- Clean process:
  - First, remove all unwanted elements from strings.
    - Punctuation
    - Speical letters: remove letters like #, @, and currency symbol.
    - Expand contracted words: we're => we are, I'm => I am , 've => have etc.
      - Note: we do not remove stop words. Removing stop words might change the result of my sentiment and mistakenly lead a text to be marked as a negative which should be orginally marked as positive.  
    - emojis => emojis does not add any value to my analysis
    - \n\t\a\r
    - url links: remove all stuff using url links
- Remove duplication
  - Remove perfect duplication (simply pd.dropduplicates)
  - Remove duplications based on the level of simiarlities (set threhold by 0.9).
    - Sentence-Transformers: text vectorization
    - Testing text similarity: use faiss-cpu / faiss-gpu package $\Rightarrow$ Facebook AI Similarity Search.
    - Sentence-RoBERTa
    - OpenAI package

### Step 1: remove unwanted users

In [88]:
# Step 1: remove unwanted users

# a list of unwanted stuff in Twitter user name
unwanted_keywords = ['上门', '上_门', '上 门', '兼', '兼_职', '兼 职', '资源', '资_源', '资 源', '美女', '美 女',
                     '美.女', '美_女', '线_下', '线下', '线 下', '线.下', '交友', '交 友', '交_友',
                     '包养', '包 养', '包_养', '外围', '外 围', '外_围',
                     '约炮', '约 炮', '学生妹', '啪', '啪_啪', '资源', '在.校', '台地',
                     '普林斯 🇬🇭🇯🇲•', '男の人', '娜娜夸库', '鵝籠書生-兔女', '郴州', '啊不不不',
                     '珠海', '德阳', '安庆', '鼓浪屿', '邪教徒', '廊坊', '兰州', '茂名',
                     '绵阳', '宁德', '天津', '温州', '武汉', '盐城']
# unwanted patterns
unwanted_pattern = '|'.join(unwanted_keywords)
# generate a list of unwanted user names:
unwanted_list = twitter_data[twitter_data['User_name']\
                             .str.contains(unwanted_pattern, regex=True)]['User_name']\
                             .unique().tolist()
unwanted_list.append(['Waziri👑', 'Remote Web3 Jobs', '統計数理研究所'])  # add one more user_name. Waziri produces irrelevant information.
# don't need these items anymore
del unwanted_keywords, unwanted_pattern

time: 111 ms (started: 2024-11-07 16:13:41 +00:00)


In [89]:
# show results(just a sample)
twitter_data[twitter_data['User_name'].isin(unwanted_list)]\
              [['Tweet_id', 'User_name', 'Text']]\
              .sample(5)

Tweet_id                                User_name  \
229141   775690551622447104                               北京洗浴上门全城安排   
55539   1603294664735481857  郴州/北湖区/苏仙区/桂阳/宜章/永兴/嘉禾/临武/汝城/桂东/安仁县/资兴市   
55129   1604438960679297026     柳州 柳城 鹿寨 融安 融水 三江 柳东 上_门 线_下 兼_职 资_源   
304078           6633734271                               北京洗浴上门全城安排   
53997   1606299965189390340    益阳 资阳区 赫山 南县 桃江 安化 沅江 上_门 线_下 兼_职 资_源   

                                                     Text  
229141  News:  "Direct access” to climate finance: les...  
55539   # Head of Norwegian group says governments bet...  
55129   # Credit spreads, climate finance, bad gentry,...  
304078  News: INTERVIEW-ADB chief says climate finance...  
53997   # Credit spreads, climate finance, bad gentry,...

time: 27.3 ms (started: 2024-11-07 16:13:41 +00:00)


### Step 2: text preprocessing

In [90]:
# df will be my working data
# removing rows that come
df = twitter_data[~twitter_data['User_name'].isin(unwanted_list)].copy()

# user_ids I want to remove
df = df[~df['User_id'].isin(["991f58f1-8958-4101-90d0-d76725aba580", "08c6ef93-a854-4047-8314-386abb4efedf", "c8c3e9c0-2eac-4fe3-bd1e-00b68fcc52b3"])]

# lower case the text
df.loc[:, 'Text_lower'] = df['Text'].str.lower()

# remove unwanted list
del unwanted_list

time: 525 ms (started: 2024-11-07 16:13:41 +00:00)


In [91]:
# rearrange columns
text_column_index = df.columns.get_loc('Text')
# make Text_lower next to text
df.insert(text_column_index+1, 'Text_lower', df.pop('Text_lower'))
# remove it since I don't need it anymore
del text_column_index

time: 10.2 ms (started: 2024-11-07 16:13:43 +00:00)


In [92]:
# see column orders
df.columns

Index(['Tweet_id', 'User_name', 'User_id', 'Quarter', 'Month', 'Date', 'Time',
       'Text', 'Text_lower', 'Lang', 'Bookmarks', 'View', 'Retweets', 'Like',
       'Quotes', 'Replies', 'Hastags'],
      dtype='object')

time: 3.17 ms (started: 2024-11-07 16:13:46 +00:00)


In [93]:
# Text preprocessing
# All text preprocess for column text_lower
import string
import re
import emoji
import zhon.hanzi
from unicodedata import normalize
import contractions

# Apply both cleaning steps
# remove http url and [\t\r\n\a]
df['Text_lower'] = df['Text_lower'].apply(lambda x: re.sub(r'[\t\r\n\a]', ' ', x))

# Remove any url link
df['Text_lower'] = df['Text_lower'].apply(lambda x: re.sub(r'(http\S+|html\S+)', '', x).strip())

# remove emojis, I hate it
df.loc[:,'Text_lower'] = df.loc[:,'Text_lower'].apply(lambda x: emoji.replace_emoji(x, replace=''))

# remove @, # and keep % replace it as percent
df.loc[:,'Text_lower'] = df.loc[:,'Text_lower'].apply(lambda x: x.replace("@", "").replace("#", "").replace("%", " percent"))

# normalise unicode text into strings, and keep it lower case
df.loc[:,'Text_lower'] = df.loc[:, 'Text_lower'].apply(lambda x: normalize('NFKD', x).lower())

# expand contraction words
# 've => have
# don't => do not etc
# change other words well.
contractions.add('co2','carbon emission')
contractions.add('ecb','european central bank')
contractions.add('ldcs','least developed countries')
contractions.add('sdg', 'sustainable development goals')
contractions.add('sdgs', 'sustainable development goals')
contractions.add('esg', 'environment, social, governance')
contractions.add('csr', 'corporate social responsibility')
df.loc[:,'Text_lower'] = df.loc[:, 'Text_lower'].apply(lambda x: contractions.fix(x))

# remove all English and Chinese punctuations
all_punctuation = ''.join([ch for ch in string.punctuation + zhon.hanzi.punctuation if ch not in '%'])
df.loc[:,'Text_lower'] = df.loc[:,'Text_lower'].apply(lambda x: x.translate(str.maketrans('', '', all_punctuation)))
del all_punctuation # don't need all_punctuation anymore

# remove unwanted symbols.
df.loc[:,'Text_lower'] = df.loc[:,'Text_lower'].apply(lambda x: re.sub(r'[^\w\s%]', '', x))

# remove unwanted white space
df.loc[:,'Text_lower'] = df.loc[:,'Text_lower'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

# keep only English letters
df['Text_lower'] = df['Text_lower'].apply(lambda x: re.sub(r'[^A-Za-z\s]', '', x))
df['Text_lower'] = df['Text_lower'].apply(lambda x: re.sub(r'\s+', ' ', x).strip())

# remove numebrs in my text. They do not provide any meaningful values
# df.loc[:, 'Text_lower'] = df.loc[:, 'Text_lower'].apply(lambda x: re.sub(r'\d+', '', x))

time: 54.9 s (started: 2024-11-07 16:13:48 +00:00)


In [94]:
df.sample(500)[['User_name', 'Time', 'Text', 'Text_lower']] # show some examples

User_name                       Time  \
231233             Institutional Investor  2016-08-16 04:30:01+00:00   
295146                        Susan Jones  2011-12-08 04:57:27+00:00   
47318                        AFRICATALYST  2023-05-24 14:48:21+00:00   
183550                   Chartered Banker  2018-07-18 08:59:21+00:00   
10126                        JCP in Essex  2024-06-14 12:50:16+00:00   
...                                   ...                        ...   
220865               Neonicotinoid Truths  2016-12-20 03:04:40+00:00   
76145                           Jot Times  2022-07-06 13:33:55+00:00   
120062                  Gas Free Pensions  2020-12-23 12:31:18+00:00   
79136   Department for Business and Trade  2022-05-18 13:03:18+00:00   
64369                  LIBF MENA and Asia  2022-09-26 08:20:58+00:00   

                                                     Text  \
231233  With green bond demand outstripping supply, st...   
295146  What's happening with Climate Finance? A New Z...   
47318   Climate finance crisis strangling Africa's pot...   
183550  FT Adviser article on the launch of our new Gr...   
10126   Green Finance Officer vacancy @WildlifeTrusts ...   
...                                                   ...   
220865  Special Climate Envoy Stern's boasts on climat...   
76145   The European Parliament approved on Wednesday ...   
120062  Loopholes to include #fossilgas as an adaptati...   
79136   📣"From renewable energy and green finance to s...   
64369   Sarah believes that implementing #sustainable ...   

                                               Text_lower  
231233  with green bond demand outstripping supply str...  
295146  what is happening with climate finance a new z...  
47318   climate finance crisis strangling africas pote...  
183550  ft adviser article on the launch of our new gr...  
10126   green finance officer vacancy wildlifetrusts h...  
...                                                   ...  
220865  special climate envoy sterns boasts on climate...  
76145   the european parliament approved on wednesday ...  
120062  loopholes to include fossilgas as an adaptatio...  
79136   from renewable energy and green finance to sus...  
64369   sarah believes that implementing sustainable f...  

[500 rows x 4 columns]

time: 19.6 ms (started: 2024-11-07 16:14:43 +00:00)


In [95]:
# row number: 304804
print(len(df))

304804
time: 328 µs (started: 2024-11-07 16:14:43 +00:00)


#### Check out duplicates
My data has following two sets of duplications:
1. Perfect duplicates.
2. Text with high level of similarity.
   - We will need to remove these two types of duplicates, accordingly.
   - I will try to use GPU to produce the similarity text check.

In [96]:
# Show some examples of duplications
df[df['Text_lower'].duplicated()][['User_name', 'Time','Text', 'Text_lower']].head(10)

User_name                       Time  \
37                                     Saferworld  2024-10-08 08:00:10+00:00   
39                     The Military Emissions Gap  2024-10-08 08:00:02+00:00   
41                       Search for Common Ground  2024-10-08 08:00:00+00:00   
42   Conflict and Environment Observatory (CEOBS)  2024-10-08 08:00:00+00:00   
51                  EQS News | UK Regulatory News  2024-10-08 07:10:45+00:00   
82                               Remote Web3 Jobs  2024-10-08 05:12:13+00:00   
94                         Wirendra Tjakrawerdaja  2024-10-08 01:24:00+00:00   
120                                      OSC News  2024-10-07 17:07:52+00:00   
131                        North West Oregonizers  2024-10-07 15:16:04+00:00   
177                                  Carbon Brief  2024-10-07 12:13:01+00:00   

                                                  Text  \
37   🕊️ We are calling for climate change policy to...   
39   🕊️We are calling for climate change policy to ...   
41   🕊️🌱 We are calling for climate change policy t...   
42   🕊️We are calling for climate change policy to ...   
51   Amundi Global Aggregate Green Bond UCITS ETF A...   
82   UNPAID VOLUNTEER - Principal Research Officers...   
94   World leaders will soon be meeting and begin t...   
120  OSC publishes approach to sustainable finance:...   
131  Vice President Harris has shown true global cl...   
177  Analysis: UK must spend £1.7bn more on nature ...   

                                            Text_lower  
37   we are calling for climate change policy to be...  
39   we are calling for climate change policy to be...  
41   we are calling for climate change policy to be...  
42   we are calling for climate change policy to be...  
51   amundi global aggregate green bond ucits etf a...  
82   unpaid volunteer principal research officers s...  
94   world leaders will soon be meeting and begin t...  
120      osc publishes approach to sustainable finance  
131  vice president harris has shown true global cl...  
177  analysis uk must spend bn more on nature by to...

time: 116 ms (started: 2024-11-07 16:14:43 +00:00)


In [97]:
# Step 1: remove duplicates
df = df.drop_duplicates('Text_lower')

# Show number of rows after duplicates
print(len(df)) # 237618 rows of data. 相较于最开始35万的数据, 已经减少了10万

237618
time: 83.6 ms (started: 2024-11-07 16:14:43 +00:00)


Remove twitter that do not contain key words from my twitter query.
After remove redudent tweet from my sample. I have 222331 data points.

In [98]:
# remove items that do not contain any of key values I used for my twitter query
# I want to my text data maintain at least one of following word.
query_keys = ['bond', 'green', 'green bond', 'green finance',
              'climate', 'climate bond', 'climate finance', 'climate action', 'climate resilience',
              'sdg', 'sdgs', 'sustainable development goals', 'sustainable', 'sustainability',
              'sustainable finance', 'sustainable investment', 'sustainable bond', 'sustainable economy',
              'environmental', 'environmental bond', 'environmental finance', 'environmental impact',
              'environmental sustainability', 'environmental policy',
              'esg', 'esg bond', 'esg finance', 'esg investment', 'esg criteria', 'esg standards',
              'clean energy', 'renewable energy', 'renewables', 'green energy', 'green infrastructure',
              'carbon neutral', 'carbon footprint', 'carbon reduction', 'carbon offset',
              'decarbonization', 'net zero', 'low-carbon',
              'zero emissions', 'eco-friendly', 'ecological',
              'greenhouse gas', 'emission reduction']


# generate a list of unwanted user names:
query_pattern = '|'.join(query_keys)

# Filter data to exclude tweets that don't contain any words from query_keys
df = df[df['Text_lower'].str.contains(query_pattern, regex=True)].reset_index(drop= True)

# remove query_keys and query_pattern, I will not use it anymore
del query_keys, query_pattern

# 222035: we have 221755 rows of data left for my next-step analysis
print(len(df))

221755
time: 1.47 s (started: 2024-11-07 16:14:43 +00:00)


I also found that texts containing the word "webinar" should be removed, as most of these entries are not relevant to our analysis and contribute unnecessary noise to the data. I will remove these tweets from my sample.

Here are some example:

|        | User_name                                        | Time                      | Text_lower                                                                                                                                                                                                                                                                     |
|-------:|:-------------------------------------------------|:--------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  72004 | British Chamber of Commerce in Indonesia         | 2021-08-24 02:55:36+00:00 | we hope it gives you the knowledge and new perspectives on green finance and that you gain more understanding on how to access itclick to watch the recording britcham britchamevent britchamindonesia greatinnovation webinar                                                 |
|  83539 | CEN and CENELEC                                  | 2021-04-20 09:46:59+00:00 | reciclajefer eucommission webinar connecting european sustainable finance to standardization full recording available on our youtube channel now sustainability sustainablefinance                                                                                             |
| 136414 | Laura Dalby                                      | 2018-12-06 21:06:29+00:00 | are you a cdnbiz interested in climate finance business opportunities with the worldbank group register for this webinar with the tcssdc                                                                                                                                       |
|  69779 | EEI International                                | 2021-11-12 19:00:00+00:00 | as cop wraps up today there is still time to register for our webinar on a cleanenergy economy the role of climate finance and the customer join us next tuesday november with speakers from ukpnnews hydroone amp pplelectricregister                                         |
|   7094 | CLEW Journalism Network                          | 2024-06-27 06:45:00+00:00 | webinars on climate amp energy todaythe state of polands energy transition forumenergiifinancing enterprises for people nature and climate in africa worldresourcesgreen shipping and sustainable finance envdefenseeurofor the full list go to                                |
| 101129 | InFiNe.lu - Inclusive Finance Network Luxembourg | 2020-09-04 12:43:36+00:00 | is pleased to partner with luxflag for the next luxflag sustainable finance webinar on th september do not forget to register financialinclusion inclusivefinance                                                                                                              |
| 106919 | IIED                                             | 2020-05-27 17:07:02+00:00 | webinar climate finance in hydropower and learning from good practice gt futuredams webinar will discuss the role of climate financiers in supporting hydropower amp look at why project developers should be interested in accessing climate finance                          |
|  37383 | Funds Europe                                     | 2023-04-28 11:11:00+00:00 | webinar as regulations on sustainable finance continue to evolve asset managers are under increasing pressure to build environment social governance portfolios that not only comply with regulations but also deliver on their clients demands and expectations register here |
| 101738 | Satellite Applications Catapult                  | 2020-08-26 10:32:13+00:00 | join ktnuk for their next thepowerofplace webinar a sustainable future with location intelligence on sept our sustainable finance lead christophe will be speaking about the geospatial solutions driving our sustainable future                                               |
| 145151 | WRI Climate                                      | 2018-06-27 14:20:14+00:00 | colombia serves as a unique example for transparency of climate finance learn why it is important with our july th webinar register now for our th july webinar                                                                                                                |

Remove "thank you +...." text => these texts are more or less related to webinar, event, chat, online boardcasting adv stuff.

1. Thank you tweet
2. Event tweet



In [101]:
thank_you_tweet = r'thank\s*.*?\b(join(?:ed|ing|s)?)\b'
df = df[~df['Text_lower'].str.contains(thank_you_tweet, regex=True)]

time: 209 ms (started: 2024-11-07 16:16:49 +00:00)


<ipython-input-101-d0c7cb00d67e>:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df = df[~df['Text_lower'].str.contains(thank_you_tweet, regex=True)]


In [118]:
event_tweet_pattern =  r'join(?:ed|ing|s)?\b(?!\s+this)(?:\s+\w+)*?\s+(?:event|events|chat|chats|lunch|lunches|webinar|webinars|initiative|initiatives|dialogue|dialogues|forum|forums|panel|panels|workshop|workshops|session|sessions)\b'

df = df[~df['Text_lower'].str.contains(event_tweet_pattern, regex = True)]

time: 204 ms (started: 2024-11-07 16:48:20 +00:00)


In [121]:
calling_tweet_pattern = r'call(?:ed|ing|s)?\b.*?\b(?:students|internships|applications|papers|zim|interns)\b'
df = df[~df['Text_lower'].str.contains(calling_tweet_pattern, regex=True)]

time: 198 ms (started: 2024-11-07 16:56:59 +00:00)


In [132]:
hire_post = r'\bhir(?:e|ing)\b(?!d)|\bjob\s+(?:alert|posting|vacancy|opening|post)\b|looking\s+to\s+(?:hire|recruit)|\bposition\s+(?:available|open|vacancy|hire)\b|vacanc(?:y|ies)\b|join\s+our\s+team\b|apply\s+now\b|\bwe\s+are\s+hiring\b|\bnew\s+opening\b'
df = df[~df['Text_lower'].str.contains(hire_post, regex = True)]

time: 3.6 s (started: 2024-11-07 17:12:35 +00:00)


In [134]:
# after remove thank you tweet, event_promoting tweet, and call for tweet
len(df) # we have 217600 tweets available

217600

time: 2.62 ms (started: 2024-11-07 17:12:54 +00:00)


In [135]:
# export the the df to local
# need to remove the raw_text to avoid formatting issue
df.drop(columns=['Text']).to_csv('Sentiment_data/Data/twitter_working_data.csv', index= False, sep=',', encoding='utf-8-sig')

time: 2.42 s (started: 2024-11-07 17:13:02 +00:00)


In [140]:
df[['User_name','User_id', 'Date','Text_lower']].sample(2000)

User_name  \
202765  1stFinancialInsights (Official) Est 2011   
76238                        EU Tax & Customs 🇪🇺   
156633                                      ICSC   
91517                               Yixi🐯ng Zeng   
206295                                Susan Ross   
...                                          ...   
219002                               Paul DeRiso   
55362                                VMSwiderski   
200769                              Ilmi Granoff   
56223                          Skanska i Sverige   
185409                      Amrita Sinha Kataria   

                                     User_id        Date  \
202765  9e66fad7-4cac-4eb3-a64c-20c5b1dd0425  2014-05-18   
76238   76dfa704-6ce5-4f44-b406-63987213c7af  2021-06-15   
156633  8fa253d5-629b-4ff1-b41c-730dc9a8f916  2017-11-14   
91517   02572484-a3ee-4c9d-9a1e-37a36d9b1e98  2021-01-27   
206295  3d681848-e2bd-4679-8413-a6be6b8b7694  2013-11-14   
...                                      ...         ...   
219002  c610573c-ef7f-4bcc-903a-e430f9c69a2e  2010-11-03   
55362   8d3e728e-f1af-43dc-8101-d6479b1c9b49  2022-07-14   
200769  607e78c8-6c8c-4236-bc2a-1b0680600c9a  2014-09-23   
56223   17f046bd-e1b4-4c24-8254-699ec49faaf7  2022-07-06   
185409  2be33620-d165-45b4-8ea3-ce0f95280e09  2015-12-07   

                                               Text_lower  
202765  the end of fossil energy the wealth of planets...  
76238   the platform for tax good governance brings to...  
156633  our associate for climate policy kairosdelacru...  
91517   the deal attracted strong interest from a dive...  
206295  cassius butts sba region iv administrator open...  
...                                                   ...  
219002  is the concept of sustainable finance working ...  
55362   i will continue to prod with a sharp stick the...  
200769  alexevansuk and we are still talking a billion...  
56223   pm today discussion on policy and regulatory d...  
185409  ccities yaleenviro city climate finance cop ci...  

[2000 rows x 4 columns]

time: 48.4 ms (started: 2024-11-07 17:16:09 +00:00)


---

### Similarity test
The simiary test will be conducted based on working data. We can set up the GPU to make my over simialrity test to work faster.  

Eventhough we have removed the perfect duplicates, we still have text that have high level similarity. Given that I have approximately 217,600 pieces of text information, my similarity test will produce a 217,600 $\times$ 217,600 matrix, resulting in about 47.349 billion data points of cosine similarity scores. To do it, I will need to use following NLP packages:
1. Package:
   1. sentence_transformer
      - Using the `SentenceTransformer` module, specifically the `all-MiniLM-L6-v2` model, I convert text data into embeddings (i.e., vectorize the text).
   2. Faiss:
      1. **Vector Normalization**: To normalize the vectors to unit length (L2 norm = 1), I use `faiss.normalize_L2(embeddings_np)`.
      2. Similarity score calculation : $ \text{cosine similarity (A, B)} = \frac{A\cdot B}{||A||\ ||B||}$.
         - $||A||$ and $||B||$ are the norms of the vectors. $\Rightarrow ||A|| = ||B|| =1$
      3. Filtering Top Similar Neighbors: FAISS allows specifying `K` to retrieve only the top K most similar neighbors, which reduces computational load and focuses on the most relevant matches.

For example: N
- A = [2,3,1]
- B = [1,1,1]

L2 norms of each vector:
- $||A|| = \sqrt{2^2 + 3^2 + 1^2} = \sqrt{14}$
- $||B|| = \sqrt{1^2 + 1^2 + 1^2} = \sqrt{3}$

Normalised ||A|| and ||B||
- $A_{normalised} = [\frac{2}{\sqrt{14}}, \frac{3}{\sqrt{14}}, \frac{1}{\sqrt{14}}]$
- $B_{normalised} = [\frac{1}{\sqrt{3}}, \frac{1}{\sqrt{3}}, \frac{1}{\sqrt{3}}]$

Cosine similarity: the similarity between text A and B
$$\text{cosine similarity (A, B)} = \frac{A\cdot B}{||A||\ ||B||}$$
$$\text{cosine similarity (A, B)} = \left( \frac{2}{\sqrt{14}} \times \frac{1}{\sqrt{3}}\right) + \left( \frac{3}{\sqrt{14}} \times \frac{1}{\sqrt{3}}\right) + \left( \frac{1}{\sqrt{14}} \times \frac{1}{\sqrt{3}}\right) $$

**Note**
- We can calculate the cosine-simiarity using GPU on google colab
- If I do not have it, we will need to change it faiss-cpu version.

### Similarity test process
- Now load google colab environment using T4 GPU
- Ret the notebook environment

In [141]:
# check out computer setups
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

# check ram size
if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

# Check if GPU is read
import torch
if torch.cuda.is_available() == True:
  print(f'{torch.cuda.get_device_name()} is ready for use')
else:
  print('Only CPU ')

del ram_gb # I don't need this variable anymore

Your runtime has 54.8 gigabytes of available RAM

You are using a high-RAM runtime!
Tesla T4 is ready for use
time: 3.48 s (started: 2024-11-07 17:16:14 +00:00)


In [142]:
# reload data once again
import numpy as np
import pandas as pd

# load data from google drive
df = pd.read_csv('Sentiment_data/Data/twitter_working_data.csv')
# reset my row index for next-step index searching job
df = df.sort_values('Text_lower').reset_index(drop = True)

# change data type: Tweet_id from int64 to string
df['Tweet_id'] = df['Tweet_id'].astype(str)
# change number types: these columns should be integers.
df[['Bookmarks', 'View', 'Retweets', 'Like','Quotes','Replies']] = df[['Bookmarks', 'View', 'Retweets', 'Like','Quotes','Replies']].astype(int)

# show data columns: we have only 'text_lower'
df.columns

Index(['Tweet_id', 'User_name', 'User_id', 'Quarter', 'Month', 'Date', 'Time',
       'Text_lower', 'Lang', 'Bookmarks', 'View', 'Retweets', 'Like', 'Quotes',
       'Replies', 'Hastags'],
      dtype='object')

time: 1.74 s (started: 2024-11-07 17:16:17 +00:00)


In [143]:
# package setups for similarity test
import torch
from sentence_transformers import SentenceTransformer
import faiss  # FAISS package
# avoid warning
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module='tqdm.autonotebook')
# Hugging face log in
from huggingface_hub import login
login('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')

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful
time: 9.56 s (started: 2024-11-07 17:16:19 +00:00)


In [144]:
# get text data ready for analysis
# I do the sort once again.
tweet_texts = df['Text_lower'].sort_values().tolist()

# Use a pre-trained BERT-based Sentence Transformer model to convert tweets to embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')

# Set up device: GPU if available, otherwise CPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = model.to(device)

# Encode tweets, use GPU if available
embeddings = model.encode(tweet_texts, convert_to_tensor=True, show_progress_bar=True, device=device)

# Convert embeddings to numpy array and normalize (required for FAISS)
embeddings_np = embeddings.cpu().numpy().astype(np.float32)
faiss.normalize_L2(embeddings_np)

# Determine whether to use GPU or CPU version of FAISS
dimension = embeddings_np.shape[1]
# if I have GPU, then we run everything using GPU. Else, we run everything using CPU
if device == 'cuda':
    # Initialize FAISS GPU resources and index
    res = faiss.StandardGpuResources()
    index = faiss.GpuIndexFlatIP(res, dimension)  # inner product search on GPU
else:
    # Use CPU FAISS index
    index = faiss.IndexFlatIP(dimension)  # inner product search on CPU

# Add embeddings to the index
index.add(embeddings_np)

# Perform a search to calculate the similarity matrix
k = 21  # Top 20 nearst neighbors. The first one is it self. So, it is always 1
sim_scores, sim_neighbor = index.search(embeddings_np, k)
# `similarity_scores` and `neighbors` contain the similarity information


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/6800 [00:00<?, ?it/s]

time: 1min 35s (started: 2024-11-07 17:16:31 +00:00)


In [145]:
# export the similarity test score and neighbor index to local
np.savetxt('Sentiment_data/Data/sim_score.npy', sim_scores)
np.savetxt('Sentiment_data/Data/sim_neighbor.npy', sim_neighbor)

time: 13.9 s (started: 2024-11-07 17:18:07 +00:00)


No need to rerun the above cosine simiarity test once again. We have used the GPU to calculate everything.

Removing similar text:
1. Export Similarity Data:
   - Use np.loadtxt() to load similarity_score and neighbor data. So, I don't have redo the cosine similarity test once again.
2. Identify Similar Text Pairs:
   1. Detect pairs of similar text based on similarity scores.

3. Deduplication Process:
   - Set a 90% cosine similarity threshold.
   - Treat posts by the same individual on the same day as duplicates.
   - Retain only the post with the longest text in each similar pair.
   - **Note**: always double check the code and data result.

   ---
  I just need to reload raw data and index data from goofle drive.


```Python
# work CPU model
# Load all necessary packages
from os import getcwd, listdir, chdir
from google.colab import drive
drive.mount('/content/drive')

# change my working directory to KJBZ_TS_2024
chdir('/content/drive/MyDrive/IES_FSV/Phd_Research/KJBZ_TS_2024')
# install packages
!pip install -r requirement_colab.txt --quiet

# package load
import numpy as np
import pandas as pd
```

In [150]:
# df load
df = pd.read_csv('Sentiment_data/Data/twitter_working_data.csv').sort_values('Text_lower').reset_index(drop = True)
tweet_text = df['Text_lower'].tolist()

# load similarity score and neighbor index accordingly.
# load and round my data
sim_scores = np.loadtxt('Sentiment_data/Data/sim_score.npy').round(2)
# load and change my data type
sim_neighbor = np.loadtxt('Sentiment_data/Data/sim_neighbor.npy').astype(int)

time: 4.36 s (started: 2024-11-07 17:18:49 +00:00)


In [151]:
# Show results.
print('Similarity score', '\n', sim_scores, '\n \n', 'Tweet item', '\n', sim_neighbor)

Similarity score 
 [[1.   0.67 0.67 ... 0.64 0.64 0.64]
 [1.   0.73 0.71 ... 0.63 0.63 0.63]
 [1.   0.66 0.66 ... 0.63 0.62 0.62]
 ...
 [1.   0.72 0.72 ... 0.67 0.67 0.67]
 [1.   0.82 0.79 ... 0.75 0.75 0.74]
 [1.   0.76 0.73 ... 0.68 0.68 0.68]] 
 
 Tweet item 
 [[     0  67437  19052 ... 119293 214183 171794]
 [     1 216402  41679 ... 101324   8492 166810]
 [     2 145534 133878 ...  58281  83341  65550]
 ...
 [217597 202960  20869 ...  16876  20895  74415]
 [217598 116785 116779 ... 116956  74153 116905]
 [217599 172128  77099 ... 205089 179166 119870]]
time: 1.41 ms (started: 2024-11-07 17:18:53 +00:00)


In [152]:
# add and change column type for filtering purpose
df['Text_length'] = df['Text_lower'].apply(len)
df['Date'] = pd.to_datetime(df['Date'])

time: 116 ms (started: 2024-11-07 17:18:56 +00:00)


In [153]:
# show tweet_text: show top 5
tweet_text[0:5]  # there are 218735 tweet texts

['a aadaption bscale up climate finance for adaptation censure landwater use for foodnutrition not biomassbeccs goodfoodmedia',
 'a aguilar ccfverdes eu taxonomy green taxonomy of colombia green bond standards mexicos taxonomy for the banking sector are the points of reference for the national taxonomy of mexico for investors sriweeks',
 'a and b so much potential for growth in these sectors first we need to transfer government assets to the private sector second is capital raising diversification less reliance on bank lending more activity on alternatives private credit green bond financing',
 'a atteridge another key gap by the way rhetoric on private climate finance amp actual flows to adaptation needs seiforum',
 'a atteridge entrenched structures that keep flows of brown finance much larger than green finance seiforum']

time: 2.87 ms (started: 2024-11-07 17:18:59 +00:00)


I need to figure out what's the best way to do this indexing.

`simiarlity_score` and `neighbor` are two numpy arraies:
1. `sim_scores` $\Rightarrow$ a 217,600 $\times$ 20 matrix of cosine similarity score for each text row.
2. `sim_neighbor` $\Rightarrow$ a matrix of tweet index corresponding to the simiarlity_score matrix.

Data filter strategy: I need to do the filter different, so i can see the difference.
1. Condition 1:
  1. Same user, tweet post dates lie within 14 days.
  2. Different user, same day (still not sure about this condition)
2. Different user, different day
  1. The threhold can be 1 week (just a test), still not sure about this condition.

Filtering data:
- set a dataframe with column 'high_sim_index', 'high_sim_neighbor' and 'high_sim_scores'.
- the row number indicates the number index of twitter text that was found with similar texts.  

In [154]:
# put all high_sim items into different list for indexing purpose.
high_sim_index = []
high_sim_neighbor = []
high_sim_scores = []
sim_score_threhold = 0.9

for i in range(sim_scores.shape[0]):
  # anything above 90% cosine similarity
  # for now, I just grab all pairs where their similarity test scores are higher than 0.85
  sim_index = np.where(sim_scores[i] >= sim_score_threhold)[0]
  # size of numpy array must > 1 and the first item must not be 0
  # two conditions must be meat
  if sim_index.size == 1 and sim_index[0] == 0:
    high_sim_index.append(np.nan)
    high_sim_neighbor.append(np.nan)
    high_sim_scores.append(np.nan)
  # else, we keep the raw and matched similar texts
  else:
    high_sim_index.append(sim_index)
    high_sim_neighbor.append(sim_neighbor[i, sim_index])
    high_sim_scores.append(sim_scores[i, sim_index])

# combine everything together
# index means, the index number of tweet_text we have. I dropped rows whether there is no similarity matches.
sim_text_dict = pd.DataFrame(list(zip(high_sim_index, high_sim_neighbor, high_sim_scores)), columns = ['high_sim_index', 'high_sim_neighbor', 'high_sim_scores']).dropna()

# show me the result
sim_text_dict    # there is 58232 rows

high_sim_index                 high_sim_neighbor  \
7              [0, 1]                       [7, 155408]   
9              [0, 1]                        [9, 18535]   
10             [0, 1]                       [10, 18513]   
15          [0, 1, 2]                  [15, 8798, 8797]   
18             [0, 1]                          [18, 19]   
...               ...                               ...   
217582   [0, 1, 2, 3]  [217582, 217583, 217584, 153127]   
217583   [0, 1, 2, 3]  [217583, 217582, 217584, 153127]   
217584      [0, 1, 2]          [217584, 217583, 217582]   
217586         [0, 1]                  [217586, 217590]   
217590         [0, 1]                  [217590, 217586]   

                high_sim_scores  
7                   [1.0, 0.96]  
9                   [1.0, 0.94]  
10                  [1.0, 0.91]  
15             [1.0, 0.96, 0.9]  
18                  [1.0, 0.99]  
...                         ...  
217582  [1.0, 0.99, 0.94, 0.93]  
217583  [1.0, 0.99, 0.94, 0.93]  
217584        [1.0, 0.94, 0.94]  
217586              [1.0, 0.93]  
217590              [1.0, 0.93]  

[58232 rows x 3 columns]

time: 865 ms (started: 2024-11-07 17:19:17 +00:00)


Example explian:

|        | high_sim_index  | high_sim_neighbor | high_sim_score|
|-------:|:--------------- |:---------------|:--------------|
|7       |[0,1]            |[7,156841]      |[1.0, 0.96]    |
|9       |[0,1]            |[9, 18640]	    |[1.0, 0.94]    |
|10      |[0,1]            |[10,18618]      |[1.0, 0.91]    |

Row 7: the tweet_text number 7 `tweet_text[7]`  is foud to have simiar text with itself and another (`high_sim_index[0,1]`) where the text index is `high_sim_neighbor[7, 156841] ` and their simiarity score is `high_sim_score \Rightarrow [1.0, 0.96]`

Filter strategy: Take tweet_text 7 as my exmaple
1. If the user is the same
2. If the tweet post dates lie within 14 days (2 weeks) window ?
3. If the similarity is above 90%

If condition 1,2,3 are all matched, we will keep either `tweet_text[7]` or `tweet_test[156841]`, based on length of text strings. And we prefer to keep the one that come with longer text.

In [155]:
# another method
from datetime import timedelta

# Step 1: Group similar texts into clusters
clusters = []    # This will store lists of indices that are similar to each other
visited = set()  # To track indices we've already processed
sim_score_threhold = 0.9 # remove anything that with cosine simiarity test > 0.9

for idx, (scores, neighbors) in enumerate(zip(sim_scores, sim_neighbor)):
    if idx in visited:
        continue

    # Create a new cluster for the current post
    cluster = [idx]
    visited.add(idx)

    current_user = df.iloc[idx]['User_id']
    current_date = df.iloc[idx]['Date']

    # Find similar neighbors that satisfy all conditions
    for neighbor_idx, score in zip(neighbors[1:], scores[1:]):
        if neighbor_idx in visited:
            continue

        if score >= sim_score_threhold:
            neighbor_user = df.iloc[neighbor_idx]['User_id']
            neighbor_date = df.iloc[neighbor_idx]['Date']

            # Check if they are from the same user and within 14 days
            if current_user == neighbor_user and abs((current_date - neighbor_date).days) <= 14:
                cluster.append(neighbor_idx)
                visited.add(neighbor_idx)

    clusters.append(cluster)

# Step 2: Retain only one text from each cluster (based on longest text, or first occurrence if tie)
rows_to_keep = set()

for cluster in clusters:
    # Sort by text length in descending order
    cluster_sorted_by_length = sorted(cluster, key=lambda x: df.iloc[x]['Text_length'], reverse=True)

    # Retain the first occurrence in case of ties in length
    rows_to_keep.add(cluster_sorted_by_length[0])


time: 1min 2s (started: 2024-11-07 17:20:04 +00:00)


In [158]:
# show my matched cluster
import random
filtered_clusters = [cluster for cluster in clusters if len(cluster) > 1]

import random
ran_sample = random.sample(filtered_clusters, min(1, len(filtered_clusters)))

# test validity of my filtering
idx = ran_sample[0][0]
print(sim_text_dict.loc[idx, 'high_sim_neighbor'])
print(sim_text_dict.loc[idx, 'high_sim_scores'])

df.loc[ran_sample[0]][['User_name', 'User_id', 'Date', 'Text_lower', 'Text_length']]

[196748 196749]
[1.   0.91]


User_name                               User_id       Date  \
196748  Climate Home News  410c523c-7568-4538-b35e-cef8cf661556 2015-07-09   
196749  Climate Home News  410c523c-7568-4538-b35e-cef8cf661556 2015-07-10   

                                               Text_lower  Text_length  
196748  unbacked climate finance initiative at real ri...           79  
196749  unbacked climate finance initiative at real ri...          106

time: 34.2 ms (started: 2024-11-07 17:22:33 +00:00)


还有什么，什么tank you for joining, are you joining , will you joining。。。 这种垃圾

In [159]:
# 手动检查
print(196748 in rows_to_keep)
print(196749 in rows_to_keep)
# print(43733 in rows_to_keep)

False
True
time: 557 µs (started: 2024-11-07 17:22:49 +00:00)
